services:
  backend:
    build: ./backend
    container_name: eu_barbeiro_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
      - redis
    volumes:
      - ./backend:/app
    networks:
      - dev_net

  web:
    build: ./web
    container_name: eu_barbeiro_web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
    networks:
      - dev_net

  db:
    image: postgres:15
    container_name: eu_barbeiro_db
    environment:
      POSTGRES_USER: barber
      POSTGRES_PASSWORD: barber123
      POSTGRES_DB: eu_barbeiro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_net

  redis:
    image: redis:7
    container_name: eu_barbeiro_redis
    ports:
      - "6379:6379"
    networks:
      - dev_net

networks:
  dev_net:

volumes:
  postgres_data:
